# Generated by Django 2.0 on 2018-05-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PiPhoto',
            new_name='PisImage',
        ),
    ]
